# Generated by Django 5.0.1 on 2024-01-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail',
            name='company_products',
            field=models.ManyToManyField(to='products.product', verbose_name='товары'),
        ),
    ]
